### ISSUE TITLE
Resin density

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/EXPOsan#15]
Why is this commented out?
https://github.com/QSD-Group/EXPOsan/blob/8420ffcf100b34ab6c98ba9922986863b69b6b2f/exposan/biogenic_refinery/_cmps.py#L152

**Comment by lsrowles** [comment]
@yalinli2 I think I was not sure if this should be dry or wet density when it was added. Would dry be best since water could be another cmp in the stream if necessary? If so, I think 750 kg/m3 is appropriate for the resin. Thanks!

**Comment by yalinli2** [comment]
@lsrowles either wet or dry is fine, it just depends on how you want to model the resin (e.g., you can model biodiesel as a mixture of components or just as a general one representing all of them), let's just go with dry. But I didn't see water added anywhere?

Additionally, can you take a look at the comments here and let me know if we still need them? Thanks!
https://github.com/QSD-Group/QSDsan/blob/gates/qsdsan/sanunits/_ion_exchanges.py

**Comment by yalinli2** [comment]
A note that 750 kg/m3 is used as the density for resin now
