### ISSUE TITLE
sysD edits in systems.py and models.py

### ISSUE THREAD

**Issue by lsrowles** [QSD-Group/EXPOsan#18]
The sysD (baseline system) in systems.py and models.py needs to be updated. 

sysD in models.py L833-841 needs to be edited to include the drying bed

https://github.com/QSD-Group/EXPOsan/blob/315338b321ece5b01625a15205a333ce3cacad64/exposan/biogenic_refinery/systems.py#L833

The updated code is as follows:
```
D5 = su.DryingBed('D5', ins=D4-0, outs=('dried_sludge', 'evaporated',
                                        'A8_CH4', 'A8_N2O'),
                  design_type='unplanted',
                  decay_k_COD=get_decay_k(tau_deg, log_deg),
                  decay_k_N=get_decay_k(tau_deg, log_deg),
                  max_CH4_emission=max_CH4_emission)

D6 = su.Mixer('D6', ins=(D2-2, D4-1, D5-2), outs=streamsD['CH4'])
D6.specification = lambda: add_fugitive_items(D5, 'CH4_item')
D6.line = 'fugitive CH4 mixer' 
        
D7 = su.Mixer('D7', ins=(D2-3, D4-2, D5-3), outs=streamsD['N2O'])
D7.specification = lambda: add_fugitive_items(D6, 'N2O_item')
D7.line = 'fugitive N2O mixer'

sysD = bst.System('sysD', path=(D1, D2, D3, D4, D5, D6, D7))
```

Also in systems.py, the unit dictionary for sysD needs to be updated. 

L876-879 needs include the units for sysD
https://github.com/QSD-Group/EXPOsan/blob/315338b321ece5b01625a15205a333ce3cacad64/exposan/biogenic_refinery/systems.py#L876

The following lines should included:
```
    'front_end': dict(sysA=(A2,), sysB=(B2,), sysC=None, sysD=(D2,)),
    'transport': dict(sysA=(A3,), sysB=(B3,B4,), sysC=None, sysD=(D3,)),
    'pretreatment': dict(sysA=(A6,), sysB=(B10,), sysC=None, sysD=(D4,)),
    'liq_treatment': dict(sysA=(A7,), sysB=(B5,B6,B7), sysC=None, sysD=(D7,)),
```

In models.py, the drying bed needs to be included prior to L878.
https://github.com/QSD-Group/EXPOsan/blob/315338b321ece5b01625a15205a333ce3cacad64/exposan/biogenic_refinery/models.py#L878

These additions are as follows:
```
    drying_bed_data = load_data(join_path(su_data_path, '_drying_bed.tsv'))
    batch_setting_unit_params(drying_bed_data, modelD, systems.D5)
```

**Comment by yalinli2** [comment]
Hi @lsrowles , thanks for the note, I've updated accordingly in 206a13a8d185d7ba81b5cf97fc6dd7f617b219cb
A couple of notes:
1. the updates you had for `modelD` regarding `D5` (drying bed) won't work because of how `sol_frac` and `bed_H` are set, I updated it to:
```python
    drying_bed_data = load_data(join_path(su_data_path, '_drying_bed.tsv'))
    D5 = systems.D5
    batch_setting_unit_params(drying_bed_data, modelD, D5, exclude=('sol_frac', 'bed_H'))

    b = D5.sol_frac
    if D5.design_type == 'unplanted':
        D = shape.Uniform(lower=0.3, upper=0.4)
    elif D5.design_type == 'planted':
        D = shape.Uniform(lower=0.4, upper=0.7)
    paramD(setter=DictAttrSetter(D5, '_sol_frac', getattr(D5, 'design_type')),
           name='sol_frac', element=D5, kind='coupled', units='fraction',
           baseline=b, distribution=D)

    b = D5.bed_H['covered']
    D = shape.Uniform(lower=0.45, upper=0.75)
    paramD(setter=DictAttrSetter(D5, 'bed_H', ('covered', 'uncovered')),
           name='non_storage_bed_H', element=D5, kind='coupled', units='m',
           baseline=b, distribution=D)

    b = D5.bed_H['storage']
    D = shape.Uniform(lower=1.2, upper=1.8)
    paramD(DictAttrSetter(D5, 'bed_H', 'storage'),
           name='storage_bed_H', element=D5, kind='coupled', units='m',
           baseline=b, distribution=D)
```
2. I also updated the ranges/baseline for the GWPs of conc_NH3, struvite, and biochar based on the notes in systems.py, you can review them at:
https://github.com/QSD-Group/EXPOsan/blob/206a13a8d185d7ba81b5cf97fc6dd7f617b219cb/exposan/biogenic_refinery/models.py#L408
3. For some simulations, the daily run time for the carbonizer base can exceed 24 hours, which is not realistic, so I now let QSDsan issue a warning and set the run time to 24, you might want to look into this
https://github.com/QSD-Group/QSDsan/blob/4cdd2a47e02dd3cdf0f032b02457cd51db16e502/qsdsan/sanunits/_carbonizer_base.py#L117

Feel free to comment back or close this issue if you think it's good!

**Comment by lsrowles** [comment]
Hello @yalinli2, thanks for the updates. all looks good to me!
1. looks good to me. I updated it on my end as well. 
2. thanks for updating those as well. It looks good
3. if I recall correctly, we had noticed that and decided to keep it that way since the assumptions were based on the manufacturer.

**Comment by yalinli2** [comment]
OK sounds good, for the last point, I now ([see here](https://github.com/QSD-Group/QSDsan/commit/8dba56ecb6c25cecd21c6c1ce5443704fd3a1a23)) let the unit keep the calculated `uptime_ratio` (with a warning) even it exceeds 1
