### ISSUE TITLE
Update `country_specific.py`

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/EXPOsan#24]
I was trying to run all the systems together for different countries, it worked perfectly for the first country, then failed as it transitioned into the second country.

The error seems to be related to impact items, essentially the impact items for the second system weren't loaded, but I'm not sure why this error could occur, I can think of ways to bypass this (e.g., force reload all impact items), but that'll lead to creation of more objects which will certainly slow the speed.

Looking back at the code - current a new model is create for each system for each country, but transitioning between countries doesn't need a new model, we can just update the model parameter values, so I'd like to update the `country_specific.py` module for this, I think the followings should be done:
- [x] Only update parameter values (baseline/distribution) when changing countries, the `create_country_specific_model` func should only create a new model when it's not provided, if a model is provided, it can just update the values
- [x] Move the `input_dct` to a centralized place (as a standalone spreadsheet) - I just realized all the `input_dct` in different systems are the same (and they should be), moving to one place will make sure that updates can be reflected across modules - users can provide different `input_dct` if they want

**Comment by haclohman** [comment]
I think that all sounds good to me! Eventually I will probably do more than the original 5 counties we have in the input dictionary (China, India, Senegal, South Africa, and Uganda). Would it be better if we transition to having all the data in a single spreadsheet and then pulling the values based on the country instead of adding it manually to the input dictionary? Similar to what we are doing for the location database in DMsan.

**Comment by yalinli2** [comment]
yep if you want to do more than 5 countries then a spreadsheet might be easier for you/users to manage the data, I'll convert the data into a spreadsheet instead of the dictionary

**Comment by yalinli2** [comment]
DONE in ba941a114e63f07991bbed84ee3b9372c4e443ba (EXPOsan) and https://github.com/QSD-Group/EXPOsan-private/commit/5ded6a2ba973c18cf08bd329184f52881901aea3!
