### ISSUE TITLE
Adjust stream price using `price_ratio` in Reclaimer contry-specific analysis

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/EXPOsan#25]
Just want to check with you @haclohman and make sure we aren't missing anything, in the Biogenic Refinery (and also NEWgenerator), we use `price_ratio` to adjust material stream price, e.g.,:
https://github.com/QSD-Group/EXPOsan/blob/5e4f2a8bb499eda521a6dd22bf41c9fd1e5c5bc1/exposan/biogenic_refinery/country_specific.py#L93

But I'm not seeing similar lines in the Reclaimer module, is it because there is no such streams to adjust?

**Comment by haclohman** [comment]
I'll look at the Reclaimer again and make sure our assumptions for updating the price ratio and the same as what we are doing for NEWgen and Biogenic Refinery. I'll look at this tomorrow.

**Comment by yalinli2** [comment]
OK great! Closing it!
