### ISSUE TITLE
Add README to modules

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/EXPOsan#37]
Hi @joyxyz1994 @jiananf2 , can you add a README for your modules (e.g., like this one for [BSM1](https://github.com/QSD-Group/EXPOsan/blob/main/exposan/bsm1/README.rst), doesn't have to be that nice, but just at least show others how to create/simulate the system...)

**Comment by yalinli2** [comment]
Also I can't remember... what is the difference between `metab` and `metab_mock`? I thought we created `metab_mock` for debugging...?

**Comment by joyxyz1994** [comment]
`metab_mock` is removed from EXPOsan because it's now obsolete. A README has been added to the `metab` module. Both operations were performed on the `metab` branch.

**Comment by yalinli2** [comment]
> `metab_mock` is removed from EXPOsan because it's now obsolete. A README has been added to the `metab` module. Both operations were performed on the `metab` branch.

awesome and thanks!!! did you push 😉 ?

**Comment by jiananf2** [comment]
A README file has been added to the `htl` module.

**Comment by yalinli2** [comment]
Thank you so much both!!! Mark it as done!
