### ISSUE TITLE
Questions for POU disinfection

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/EXPOsan#39]
@lsrowles 
Working on updating the POU disinfection module (see `pou_disinfection` branch), listing the potential bugs to be confirmed, because your original codes aren't on GitHub, I have to use screenshots here:

---
- [x] This has been fixed
---
1. In AgNP_CWF, I think you are trying to set the lifetime so that if only one of turbidity>10 or hardness>60 is true, lifetime is 1.5; if both turbidity>10 AND hardness>60, lifetime is 0.5. However, the way it is written, you'll never make lifetime to be 0.5
![image](https://github.com/QSD-Group/EXPOsan/assets/49011373/e7068256-d489-4a60-a4d5-de7c91b7b734)

```python
>>> def test(turbidity, hardness):
>>>     print(f'turbidity is {turbidity}, hardness is {hardness}')
>>>     if turbidity <= 10 and hardness <= 60:
>>>         print('lifetime is 2')
>>>     elif turbidity > 10 or hardness > 60:
>>>         print('lifetime is 1.5')
>>>     elif turbidity > 10 and hardness > 60:
>>>         print('lifetime is 0.5')

>>> test(5, 5)
turbidity is 5, hardness is 5
lifetime is 2
>>> test(15, 5)
turbidity is 15, hardness is 5
lifetime is 1.5
>>> test(15, 65)
turbidity is 15, hardness is 65
lifetime is 1.5
```

Instead, you should do this:
```python
>>> def test2(turbidity, hardness):
>>>     print(f'turbidity is {turbidity}, hardness is {hardness}')
>>>     if turbidity <= 10 and hardness <= 60:
>>>         print('lifetime is 2')
>>>     elif turbidity > 10 and hardness > 60:
>>>         print('lifetime is 0.5')
>>>     else: print('lifetime is 1.5')
        
>>> test2(5, 5)
turbidity is 5, hardness is 5
lifetime is 2
>>> test2(15, 5)
turbidity is 15, hardness is 5
lifetime is 1.5
>>> test2(15, 65)
turbidity is 15, hardness is 65
lifetime is 0.5
```

**Comment by yalinli2** [comment]
2. Related to `POUChlorination` on NaClO dose, the way it's written, NaClO dose will keep doubling. Will explain more in a meeting

**Comment by yalinli2** [comment]
3. Same for `POU_UV` on `lamp_life_span`

**Comment by lsrowles** [comment]
@yalinli2 
I agree with your edit for pou_disinfection. Good catch on that. 

I will follow up with you on the other two points.

**Comment by yalinli2** [comment]
4. Is the CF of stainless steel from ecoinvent 3.9 (as others) or from Trimmer et al. (3.2 I think?)

**Comment by yalinli2** [comment]
5. Might need to update the sigma value in uncertainty analysis for household size
6. Has p-value from Spearman been considered?

**Comment by yalinli2** [comment]
7. In the impact item datasheet, is the functional unit of UVlamp/LED per kg or each?

**Comment by yalinli2** [comment]
8, Price for Polyethylene is 0?

**Comment by yalinli2** [comment]
9. For POU chlorination, polyethylene in the container and for the Cl bottle should be counted together

**Comment by yalinli2** [comment]
TBD, should update uncertainty.py and add notes in the script
--------------------------------------------------------------------
10. No need to analyze for different population size (since it won't affect the results at all)

**Comment by yalinli2** [comment]
Fixed, but should do a manual check with baseline values
---------------------------------------------------------------
11. Incorrect UV run time & electricity calculation
@lsrowles see what I changed in 1a4fe98 (totally found it out by coincidence), but `F_vol` is in m3 so the previous calculation was off by 1000, but the impacts on results were <1%

**Comment by yalinli2** [comment]
All tasks done, closing this issue!
