### ISSUE TITLE
Questions for BSM2 module

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/EXPOsan#44]
Documenting questions related to implementing the BSM2 configuration in EXPOsan: https://github.com/QSD-Group/EXPOsan/tree/bsm2/exposan/bsm2

Tables, etc. below refer to the BSM2 report if not otherwise noted: http://iwa-mia.org/wp-content/uploads/2022/09/TR3_BSM_TG_Tech_Report_no_3_BSM2_General_Description.pdf

**Comment by yalinli2** [comment]
# ADM

- [ ] Need to figure out where all the parameters in Tables 5-8 are set for `adm1`/`AnaerobicCSTR`

**Comment by yalinli2** [comment]
# Primary Clarifier
- [ ] Need to figure out where f_X and f_XS are set
- [ ] Not sure why HRT is set, rather than V

**Comment by yalinli2** [comment]
@joyxyz1994 

Currently the `ASM2ADM` and `ADM2ASM` junctions work about right, still minor differences in some components but largely match the results.

After providing some initial conditions the system can miraculously run, but the results are awfully wrong...

**Comment by joyxyz1994** [comment]
Would you be able to join the office hour today? If no one shows up, we can work on this together.

> @joyxyz1994
> 
> Currently the `ASM2ADM` and `ADM2ASM` junctions work about right, still minor differences in some components but largely match the results.
> 
> After providing some initial conditions the system can miraculously run, but the results are awfully wrong...

**Comment by yalinli2** [comment]
@joyxyz1994 I tried to run the test for the `bsm2` module but it didn't pass... which branches of QSDsan/EXPOsan should I be using?

If you've gotten the results close enough to the matlab model, can you send in a PR to merge into main?

**Comment by joyxyz1994** [comment]
I used `qsdsan@metro-bsm2` and `exposan@bsm2`. The maximum relative error I got was around 0.018. I didn't merge because I haven't checked the other sludge treatment units that Saumitra developed yet. Would you prefer we merge anyway?

**Comment by yalinli2** [comment]
Ah if that's the case let's wait till that's figured out - I just realized that we need to merge in the updates in ***@***.***

I'll rerun the tests locally, I thought I was using the exact same branches as you and I pulled in the recent changes....

________________________________

**Comment by yalinli2** [comment]
Losing track on this issue... but seems like @joyxyz1994 you've finished and merged in `bsm2`?

**Comment by joyxyz1994** [comment]
ahh yes, we can close this issue now
